server:
  port: 9191
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://containers-us-west-34.railway.app:7195/railway
    username: root
    password: aRzRsFkq4FIHatqSLKzt
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  application:
    name: NEWSPAPER-SERVICE
