server:
  port: 9191
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://bqyncj75f8cdjhsjtgvq-mysql.services.clever-cloud.com:3306/bqyncj75f8cdjhsjtgvq
    username: up9iezasierjtuhb
    password: gUjbBRbphM0CiKiukPrT
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
  application:
    name: NEWSPAPER-SERVICE
